[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/aylien/go-pingdom"

[prune]
  go-tests = true
  unused-packages = true
